plugins { id 'com.android.application' }

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('keystore.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace 'com.local.kimiapp'
    compileSdk 35

    defaultConfig {
        applicationId 'com.local.kimiapp'
        minSdk 26
        targetSdk 34
        versionCode 33
        versionName '2.4.2'
    }

    signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile rootProject.file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
    implementation 'androidx.webkit:webkit:1.12.1'
    implementation 'io.github.petterpx:floatingx:2.3.7'
    implementation 'androidx.fragment:fragment:1.8.9'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
